Repository ehk9000/Palette-Picker-UI, pull requests merged in 2019-07, with the labels that each got.

#12 base file tree, base grid styling
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/app/App.js
  src/components/app/App.test.js
  src/components/app/_App.scss
  src/index.css
  src/index.js
  src/logo.svg
  src/styles/index.scss
  src/styles/normalize.scss
Labels: enhancement, good first issue

#13 added files that may be needed
  src/components/control_form/_control_form.scss
  src/components/control_form/control_form.test.js
  src/components/control_form/index.js
  src/components/display_color/_display_color.scss
  src/components/display_color/display_color.test.js
  src/components/display_color/index.js
  src/components/drop_down/_drop_down.scss
  src/components/drop_down/drop_down.test.js
  src/components/drop_down/index.js
  src/components/hex_input/_hex_input.scss
  src/components/hex_input/hex_input.test.js
  src/components/hex_input/index.js
  src/components/projects_list/_projects_list.scss
  src/components/projects_list/index.js
  src/components/projects_list/projects_list.test.js
  src/components/recent_list/_recent_list.scss
  src/components/recent_list/index.js
  src/components/recent_list/recent_list.test.js
Labels: enhancement

#15 Router setup
  package-lock.json
  package.json
  pull_requests_template.md
  src/components/app/App.js
  src/index.js
Labels: enhancement, good first issue

#16 Create Header and Dropdown components
  public/index.html
  src/components/app/App.js
  src/components/drop_down/index.js
  src/components/header/_header.scss
  src/components/header/header.test.js
  src/components/header/index.js
Labels: good first issue

#18 Revamp Project Form, Includes ColorGenerator component
  src/components/app/App.js
  src/components/color_generator/index.js
  src/components/control_form/index.js
Labels: enhancement, good first issue, help wanted

#20 Styling
  src/components/app/App.js
  src/components/app/_App.scss
  src/components/color_generator/index.js
  src/components/control_form/_control_form.scss
  src/components/control_form/index.js
  src/components/drop_down/index.js
  src/components/header/_header.scss
  src/styles/index.scss
  src/styles/variable.scss
Labels: enhancement, good first issue

#24 Styling
  src/components/Project/index.js
  src/components/app/App.js
  src/components/appleSVG/index.js
  src/components/color_generator/_color_generator.scss
  src/components/color_generator/color_generator.test.js
  src/components/color_generator/index.js
  src/components/control_form/_control_form.scss
  src/components/header/_header.scss
  src/components/header/index.js
  src/containers/Project_list/index.js
  src/imgs/apple.svg
  src/styles/index.scss
Labels: enhancement, good first issue

#29 Wip
  src/actions/index.js
  src/components/Project/index.js
  src/components/color_generator/index.js
  src/components/control_form/index.js
  src/reducers/currentPaletteReducer.js
  src/reducers/currentProjectReducer.js
  src/reducers/index.js
Labels: bug, enhancement, good first issue, help wanted
